### ISSUE TITLE
Awaitable mocks

### ISSUE THREAD

**Issue by ekzyis** [ekzyis/physicsbot#44]
While testing the following function:

```python
async def add_role_to_member(member, role_id):
    """Adds the role given by its id to the member.
    The role id must be from a role of the guild of the member (if that's not obvious)"""
    role = member.guild.get_role(int(role_id))
    await member.add_roles(role)
```
with this test code:
```python
import inspect
from unittest import mock

import aiounittest

# noinspection PyUnresolvedReferences
import test.context
from src.util import add_role_to_member


class TestAddRoleToMember(aiounittest.AsyncTestCase):

    @mock.patch('discord.Role')
    @mock.patch('discord.Member')
    @mock.patch('discord.Guild')
    async def test_add_role_to_member_adds_role_to_member_with_given_role_id_as_string(self, guild, member, role):
        guild.get_role.return_value = role
        member.guild = guild
        await add_role_to_member(member, '12345')
        member.add_roles.assert_called_with(role)

```
(test execution with `python -m unittest`)

I encountered following error:

```
======================================================================
ERROR: test_add_role_to_member_adds_role_to_member_with_given_role_id_as_string (test.test_add_role_to_member.TestAddRoleToMember)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ekzyis/Programming/physicsbot/venv/lib/python3.8/site-packages/aiounittest/helpers.py", line 138, in wrapper
    return loop.run_until_complete(future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/unittest/mock.py", line 1365, in patched
    return await func(*newargs, **newkeywargs)
  File "/home/ekzyis/Programming/physicsbot/test/test_add_role_to_member.py", line 19, in test_add_role_to_member_adds_role_to_member_with_given_role_id_as_string
    await add_role_to_member(member, '12345')
  File "/home/ekzyis/Programming/physicsbot/src/util.py", line 10, in add_role_to_member
    await member.add_roles(role)
TypeError: object MagicMock can't be used in 'await' expression

----------------------------------------------------------------------
```

According to https://docs.python.org/3/library/unittest.mock.html#unittest.mock.AsyncMock

the `unittest` package contains an AsyncMock.

According to https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch
> If new is omitted, then the target is replaced with an AsyncMock if the patched object is an async function or a MagicMock otherwise.

using the mock patch decorator with an async function (which is the case here), an AsyncMock should be passed to the function. This seems to not be the case since else I would have gotten an AsyncMock which would be awaitable. Maybe I understand the text wrong?

Anyway, when trying to explicitly use the AsyncMock with new like this:

```python
@mock.patch('discord.Role')
    @mock.patch('discord.Member', new=AsyncMock)
    @mock.patch('discord.Guild')
    async def test_add_role_to_member_adds_role_to_member_with_given_role_id_as_string(self, guild, member, role):
        guild.get_role.return_value = role
        member.guild = guild
        await add_role_to_member(member, '12345')
        member.add_roles.assert_called_with(role)
```

I get this error which makes no sense to me:

```
======================================================================
ERROR: test_add_role_to_member_adds_role_to_member_with_given_role_id_as_string (test.test_add_role_to_member.TestAddRoleToMember)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ekzyis/Programming/physicsbot/venv/lib/python3.8/site-packages/aiounittest/helpers.py", line 138, in wrapper
    return loop.run_until_complete(future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/unittest/mock.py", line 1365, in patched
    return await func(*newargs, **newkeywargs)
TypeError: test_add_role_to_member_adds_role_to_member_with_given_role_id_as_string() missing 1 required positional argument: 'role'

----------------------------------------------------------------------
```

Changing the order leads to other confusing TypeError which seem to have no system:

When using this order:
```python
    @mock.patch('discord.Role')
    @mock.patch('discord.Member')
    @mock.patch('discord.Guild', new=AsyncMock)
```
or this order:
```python
    @mock.patch('discord.Role', new=AsyncMock)
    @mock.patch('discord.Member')
    @mock.patch('discord.Guild')
```
the same error message is produced.

Any combination of two `new=AsyncMock` results in
```
TypeError: test_add_role_to_member_adds_role_to_member_with_given_role_id_as_string() missing 2 required positional arguments: 'member' and 'role'
```

while using `new` in all patch decorators results in
```
TypeError: test_add_role_to_member_adds_role_to_member_with_given_role_id_as_string() missing 3 required positional arguments: 'guild', 'member', and 'role'
```

**Comment by ekzyis** [comment]
Maybe use [asynctest](https://asynctest.readthedocs.io/) instead of [aiounittest](https://pypi.org/project/aiounittest/)?

**Comment by ekzyis** [comment]
Ouuh, just noticed that `aiounittest` provides a wrapper to make everything awaitable!

https://aiounittest.readthedocs.io/en/latest/futurized.html

**Comment by ekzyis** [comment]
I guess this can be closed since I am already using awaitable mocks?
