### ISSUE TITLE
AttributeError: 'Member' object has no attribute 'user'

### ISSUE THREAD

**Issue by ekzyis** [ekzyis/physicsbot#50]
Just found in the logs:

```
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/physicsbot/src/bot.py", line 29, in on_member_join
    self.logger.info('User %s has joined guild %s' % (member.user.name, member.guild))
AttributeError: 'Member' object has no attribute 'user'
```

**Comment by ekzyis** [comment]
Closing because old
